name: Testing self-hosted runner

on: [push]

jobs:
  hello:
    runs-on: self-hosted
    steps:
      - name: Say hello
        run: echo "Hello cloud gurus"
      - name: Say your machine name
        run: echo $HOSTNAME

